'use client';

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { usePathname } from "next/navigation";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const pathname = usePathname();

  return (
    <html lang="en">
      <head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <NextTopLoader
          color="#D396FF"
          initialPosition={0.08}
          crawlSpeed={100}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={100}
        // shadow="0 0 10px #A020F0,0 0 5px #A020F0"
        />
        {pathname !== '/' && <Navbar />}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
