'use client';

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const pathname = usePathname();

  return (
    <html lang="en">
      <head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        {pathname !== '/' && <Navbar />}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
